# Generated by Django 3.2 on 2022-03-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('subject', models.TextField()),
                ('publisher', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('numberOfpages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('isReferenceOnly', models.BooleanField()),
                ('borrowed', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('dateOfPurchase', models.DateTimeField()),
                ('publicationsDate', models.DateTimeField()),
            ],
        ),
    ]
