# Generated by Django 3.2 on 2022-03-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='status',
        ),
    ]
