# Generated by Django 3.2 on 2022-03-25 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='barcode',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
