# Generated by Django 3.2 on 2022-03-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220317_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='numberOfpages',
            new_name='number_of_pages',
        ),
        migrations.RenameField(
            model_name='bookitem',
            old_name='dateOfPurchase',
            new_name='date_of_purchase',
        ),
        migrations.RenameField(
            model_name='bookitem',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='bookitem',
            old_name='isReferenceOnly',
            new_name='is_reference_only',
        ),
        migrations.RenameField(
            model_name='bookitem',
            old_name='publicationsDate',
            new_name='publication_date',
        ),
    ]
